name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write # NPM releases

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-pr:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/on-workflow-call-validate-pr-title.yml
    secrets: inherit
  format:
    uses: ./.github/workflows/on-workflow-call-format.yml
  lint:
    uses: ./.github/workflows/on-workflow-call-lint.yml
  dependencies:
    uses: ./.github/workflows/on-workflow-call-deps.yml
  test:
    uses: ./.github/workflows/on-workflow-call-test.yml

  mergeable:
    if: always()
    needs:
      - lint
      - dependencies
      - format
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: re-actors/alls-green@release/v1
        id: all-green
        with:
          jobs: ${{ toJSON(needs)}}

  docs:
    if: github.ref == 'refs/heads/main'
    needs: [mergeable]
    uses: ./.github/workflows/docs.yml
    secrets: inherit

  npm:
    if: github.ref == 'refs/heads/main'
    needs: [mergeable]
    uses: ./.github/workflows/on-workflow-call-release.yml
    secrets: inherit
