name: NPM

on:
  workflow_dispatch:
  workflow_call:

permissions:
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: ./.github/actions/prepare

      - name: Build
        run: pnpm run build

      - name: Publish
        run: |
          if ! pnpm can-npm-publish; then
            exit 0
          fi

          pnpm publish --access public --no-git-checks
